#include "SMTPasses.h"
#include "LoopPasses.h"
#include "../utils/Matcher.h"
#include <climits>
#include <cstdlib>
#include <cstring>
#include <map>
#include <set>
#include <unordered_map>
#include <unordered_set>
#include <vector>

using namespace sys;
using namespace smt;

// Generated by expr-gen.ts
// All combinations up to 2 instructions from the following:
//  add, sub, and, or, xor
SynthConstArray::SynthConstArray(ModuleOp *module): Pass(module) {
  auto _x = ctx.create(BvExpr::Var, "x");
  auto _c0 = ctx.create(BvExpr::Var, "c0");
  auto _c1 = ctx.create(BvExpr::Var, "c1");
  // === Manually added ===
  candidates.reserve(150);
  candidates.push_back(_x);
  // === Done ===
  candidates.push_back(ctx.create(BvExpr::Add, _x, _x));
  candidates.push_back(ctx.create(BvExpr::Add, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, _x));
  candidates.push_back(ctx.create(BvExpr::And, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Or, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, _c0));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Add, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::And, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Or, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _x, ctx.create(BvExpr::Xor, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Add, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::And, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Or, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, _c0, ctx.create(BvExpr::Xor, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Add, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::And, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Or, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _x, ctx.create(BvExpr::Xor, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Add, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::And, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Or, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Sub, _c0, ctx.create(BvExpr::Xor, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Add, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::And, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Or, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _x, ctx.create(BvExpr::Xor, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Add, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::And, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Or, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::And, _c0, ctx.create(BvExpr::Xor, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Add, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::And, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Or, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _x, ctx.create(BvExpr::Xor, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Add, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::And, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Or, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Or, _c0, ctx.create(BvExpr::Xor, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Add, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Sub, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Sub, _c0, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::And, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Or, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _x, ctx.create(BvExpr::Xor, _x, _c0)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Add, _x, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Add, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Sub, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Sub, _c1, _x)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::And, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Or, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Xor, _c0, ctx.create(BvExpr::Xor, _x, _c1)));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Add, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Add, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::And, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::And, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Or, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Or, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Xor, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Add, ctx.create(BvExpr::Xor, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Add, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Add, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::And, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::And, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Or, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Or, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Xor, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Sub, ctx.create(BvExpr::Xor, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Add, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Add, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::And, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::And, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Or, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Or, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Xor, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::And, ctx.create(BvExpr::Xor, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Add, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Add, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::And, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::And, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Or, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Or, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Xor, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Or, ctx.create(BvExpr::Xor, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Add, _x, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Add, _x, _x), _c0));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Add, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Add, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _c0, _x), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Sub, _c0, _x), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::And, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::And, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Or, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Or, _x, _c0), _c1));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Xor, _x, _c0), _x));
  candidates.push_back(ctx.create(BvExpr::Xor, ctx.create(BvExpr::Xor, _x, _c0), _c1));
}

namespace {

bool envEnabled(const char *name, bool fallback) {
  const char *raw = std::getenv(name);
  if (!raw || !raw[0])
    return fallback;
  return std::strcmp(raw, "0") != 0 && std::strcmp(raw, "false") != 0 &&
         std::strcmp(raw, "FALSE") != 0;
}

int clampToInt(long long v) {
  if (v > INT_MAX)
    return INT_MAX;
  if (v < INT_MIN)
    return INT_MIN;
  return (int) v;
}

struct LinearExpr {
  long long constant = 0;
  std::map<Op*, long long> terms;
  bool valid = true;
};

void mergeLinear(LinearExpr &dst, const LinearExpr &src, long long scale = 1) {
  if (!dst.valid || !src.valid)
    return;
  dst.constant += src.constant * scale;
  for (auto [op, coeff] : src.terms)
    dst.terms[op] += coeff * scale;
}

void canonicalizeLinear(LinearExpr &expr) {
  for (auto it = expr.terms.begin(); it != expr.terms.end();) {
    if (it->second == 0)
      it = expr.terms.erase(it);
    else
      ++it;
  }
}

bool collectLinear(Op *op, LinearExpr &out, std::unordered_set<Op*> &visiting) {
  if (!out.valid || !op)
    return out.valid = false;
  if (isa<IntOp>(op)) {
    out.constant += V(op);
    return true;
  }
  if (visiting.count(op))
    return out.valid = false;

  visiting.insert(op);
  bool ok = true;
  if (isa<AddIOp>(op) || isa<AddLOp>(op) || isa<SubIOp>(op) || isa<SubLOp>(op)) {
    LinearExpr lhs, rhs;
    ok &= collectLinear(op->DEF(0), lhs, visiting);
    ok &= collectLinear(op->DEF(1), rhs, visiting);
    if (ok) {
      mergeLinear(out, lhs);
      mergeLinear(out, rhs, (isa<AddIOp>(op) || isa<AddLOp>(op)) ? 1 : -1);
    }
  } else if (isa<MinusOp>(op)) {
    LinearExpr x;
    ok &= collectLinear(op->DEF(), x, visiting);
    if (ok)
      mergeLinear(out, x, -1);
  } else if (isa<MulIOp>(op) || isa<MulLOp>(op)) {
    Op *lhs = op->DEF(0), *rhs = op->DEF(1);
    if (isa<IntOp>(lhs) || isa<IntOp>(rhs)) {
      int factor = isa<IntOp>(lhs) ? V(lhs) : V(rhs);
      Op *other = isa<IntOp>(lhs) ? rhs : lhs;
      LinearExpr x;
      ok &= collectLinear(other, x, visiting);
      if (ok)
        mergeLinear(out, x, factor);
    } else {
      out.terms[op] += 1;
    }
  } else if (isa<PhiOp>(op) || op->getResultType() == Value::i32) {
    out.terms[op] += 1;
  } else {
    ok = false;
  }

  visiting.erase(op);
  if (!ok)
    out.valid = false;
  return out.valid;
}

bool divideByElementSize(LinearExpr &bytes) {
  canonicalizeLinear(bytes);
  if (bytes.constant % 4 != 0)
    return false;
  bytes.constant /= 4;
  for (auto &[_, coeff] : bytes.terms) {
    if (coeff % 4 != 0)
      return false;
    coeff /= 4;
  }
  canonicalizeLinear(bytes);
  return true;
}

bool directIndexExpr(Op *addr, const std::string &global, LinearExpr &elems,
                     std::unordered_set<Op*> &visiting) {
  if (!addr || visiting.count(addr))
    return false;
  if (isa<GetGlobalOp>(addr))
    return NAME(addr) == global;
  if (!isa<AddLOp>(addr) && !isa<SubLOp>(addr))
    return false;

  visiting.insert(addr);
  auto trySide = [&](int baseIdx, int offsetIdx, long long sign) {
    LinearExpr baseElems;
    std::unordered_set<Op*> nested;
    if (!directIndexExpr(addr->DEF(baseIdx), global, baseElems, nested))
      return false;
    LinearExpr bytes;
    std::unordered_set<Op*> linearVisiting;
    if (!collectLinear(addr->DEF(offsetIdx), bytes, linearVisiting) ||
        !divideByElementSize(bytes))
      return false;
    elems = baseElems;
    mergeLinear(elems, bytes, sign);
    canonicalizeLinear(elems);
    return elems.valid;
  };

  bool ok = false;
  if (isa<AddLOp>(addr))
    ok = trySide(0, 1, 1) || trySide(1, 0, 1);
  else
    ok = trySide(0, 1, -1);
  visiting.erase(addr);
  return ok;
}

bool simpleAffineIndex(const LinearExpr &expr) {
  int nonZeroTerms = 0;
  for (auto [_, coeff] : expr.terms)
    if (coeff != 0)
      nonZeroTerms++;
  return nonZeroTerms <= 1;
}

Op *buildIndexValue(Builder &builder, const LinearExpr &expr, Op *before) {
  builder.setBeforeOp(before);
  Op *acc = nullptr;
  auto append = [&](Op *term) {
    if (!acc)
      acc = term;
    else
      acc = builder.create<AddIOp>(std::vector<Value>{ acc, term });
  };

  for (auto [term, coeff] : expr.terms) {
    if (!coeff)
      continue;
    Op *scaled = term;
    if (coeff != 1) {
      auto c = builder.create<IntOp>({ new IntAttr(clampToInt(coeff)) });
      scaled = builder.create<MulIOp>({ term, c });
    }
    append(scaled);
  }
  if (expr.constant != 0) {
    auto c = builder.create<IntOp>({ new IntAttr(clampToInt(expr.constant)) });
    append(c);
  }
  if (!acc)
    acc = builder.create<IntOp>({ new IntAttr(0) });
  return acc;
}

bool isPointerStep(Op *value, Op *phi, long long &stepBytes) {
  if (!isa<AddLOp>(value) && !isa<SubLOp>(value))
    return false;
  if (value->DEF(0) == phi) {
    if (!isa<IntOp>(value->DEF(1)))
      return false;
    stepBytes = isa<AddLOp>(value) ? V(value->DEF(1)) : -V(value->DEF(1));
    return true;
  }
  if (isa<AddLOp>(value) && value->DEF(1) == phi && isa<IntOp>(value->DEF(0))) {
    stepBytes = V(value->DEF(0));
    return true;
  }
  return false;
}

Op *pointerPhiIndex(Op *phi, const std::string &global, Builder &builder,
                    std::unordered_map<Op*, Op*> &cache) {
  if (!isa<PhiOp>(phi) || phi->getOperandCount() != 2)
    return nullptr;
  if (cache.count(phi))
    return cache[phi];

  for (int latchIdx = 0; latchIdx < 2; ++latchIdx) {
    long long stepBytes = 0;
    auto latchValue = phi->DEF(latchIdx);
    if (!isPointerStep(latchValue, phi, stepBytes) || stepBytes % 4 != 0)
      continue;

    int startIdx = 1 - latchIdx;
    LinearExpr startElems;
    std::unordered_set<Op*> visiting;
    if (!directIndexExpr(phi->DEF(startIdx), global, startElems, visiting) ||
        !startElems.valid || !startElems.terms.empty())
      continue;

    builder.setBeforeOp(phi->DEF(startIdx));
    auto start = builder.create<IntOp>({ new IntAttr(clampToInt(startElems.constant)) });

    builder.setBeforeOp(phi);
    auto indexPhi = builder.create<PhiOp>({ start },
                                          { new FromAttr(FROM(phi->getAttrs()[startIdx])) });
    cache[phi] = indexPhi;

    builder.setBeforeOp(latchValue);
    auto step = builder.create<IntOp>({ new IntAttr(clampToInt(stepBytes / 4)) });
    auto next = builder.create<AddIOp>({ indexPhi, step });
    indexPhi->pushOperand(next);
    indexPhi->add<FromAttr>(FROM(phi->getAttrs()[latchIdx]));
    return indexPhi;
  }
  return nullptr;
}

Op *resolveIndexValue(Op *addr, const std::string &global, Op *before,
                      Builder &builder, std::unordered_map<Op*, Op*> &phiCache) {
  LinearExpr elems;
  std::unordered_set<Op*> visiting;
  if (directIndexExpr(addr, global, elems, visiting) && elems.valid &&
      simpleAffineIndex(elems))
    return buildIndexValue(builder, elems, before);

  if (auto indexPhi = pointerPhiIndex(addr, global, builder, phiCache))
    return indexPhi;

  if (isa<AddLOp>(addr) || isa<SubLOp>(addr)) {
    for (int phiIdx = 0; phiIdx < 2; ++phiIdx) {
      if (isa<SubLOp>(addr) && phiIdx != 0)
        continue;
      auto indexPhi = pointerPhiIndex(addr->DEF(phiIdx), global, builder, phiCache);
      if (!indexPhi)
        continue;
      LinearExpr bytes;
      std::unordered_set<Op*> linearVisiting;
      if (!collectLinear(addr->DEF(1 - phiIdx), bytes, linearVisiting) ||
          !divideByElementSize(bytes))
        continue;
      LinearExpr elems2;
      elems2.terms[indexPhi] = 1;
      mergeLinear(elems2, bytes, isa<AddLOp>(addr) ? 1 : -1);
      canonicalizeLinear(elems2);
      if (simpleAffineIndex(elems2))
        return buildIndexValue(builder, elems2, before);
    }
  }
  return nullptr;
}

bool scanReadonlyUses(Op *root, std::vector<LoadOp*> &loads,
                      std::unordered_set<Op*> &visited) {
  if (!root || visited.count(root))
    return true;
  visited.insert(root);
  auto uses = root->getUses();
  for (auto use : uses) {
    if (isa<LoadOp>(use) && use->DEF(0) == root) {
      loads.push_back(cast<LoadOp>(use));
      continue;
    }
    if (isa<StoreOp>(use))
      return false;
    if (isa<CallOp>(use) || isa<ReturnOp>(use))
      return false;
    if (isa<AddLOp>(use) || isa<SubLOp>(use) || isa<PhiOp>(use)) {
      if (!scanReadonlyUses(use, loads, visited))
        return false;
      continue;
    }
    return false;
  }
  return true;
}

}

Op *SynthConstArray::reconstruct(smt::BvExpr *expr, Op *subscript, int c0, int c1) {
  switch (expr->ty) {
  case BvExpr::Var:
    if (expr->name == "x")
      return subscript;
    if (expr->name == "c0")
      return builder.create<IntOp>({ new IntAttr(c0) });
    if (expr->name == "c1")
      return builder.create<IntOp>({ new IntAttr(c1) });
    assert(false);
    std::abort();
  case BvExpr::Add: {
    Value l = reconstruct(expr->l, subscript, c0, c1);
    Value r = reconstruct(expr->r, subscript, c0, c1);
    return builder.create<AddIOp>({ l, r });
  }
  case BvExpr::Sub: {
    Value l = reconstruct(expr->l, subscript, c0, c1);
    Value r = reconstruct(expr->r, subscript, c0, c1);
    return builder.create<SubIOp>({ l, r });
  }
  case BvExpr::And: {
    Value l = reconstruct(expr->l, subscript, c0, c1);
    Value r = reconstruct(expr->r, subscript, c0, c1);
    return builder.create<AndIOp>({ l, r });
  }
  case BvExpr::Or: {
    Value l = reconstruct(expr->l, subscript, c0, c1);
    Value r = reconstruct(expr->r, subscript, c0, c1);
    return builder.create<OrIOp>({ l, r });
  }
  case BvExpr::Xor: {
    Value l = reconstruct(expr->l, subscript, c0, c1);
    Value r = reconstruct(expr->r, subscript, c0, c1);
    return builder.create<XorIOp>({ l, r });
  }
  default:
    assert(false);
    std::abort();
  }
}

void SynthConstArray::run() {
  // Reference-compatible default: only source constants with a full-table
  // proof may be synthesized, and every load still needs an affine IR index.
  if (!envEnabled("SISY_ENABLE_SYNTH_CONST_ARRAY", true))
    return;

  auto gMap = getGlobalMap();
  auto gets = module->findAll<GetGlobalOp>();
  std::unordered_map<Op*, Op*> pointerPhiCache;

  for (auto [k, v] : gMap) {
    if (v->has<FloatArrayAttr>())
      continue;

    auto iarr = v->get<IntArrayAttr>();
    if (iarr->allZero)
      continue;

    auto ptr = iarr->vi;
    auto size = iarr->size;
    if (!ptr || size <= 0 || size > 256)
      continue;
    arraysConsidered++;

    std::vector<LoadOp*> loads;
    bool readonly = true;
    for (auto get : gets) {
      if (NAME(get) != k)
        continue;
      std::unordered_set<Op*> visited;
      if (!scanReadonlyUses(get, loads, visited)) {
        readonly = false;
        break;
      }
    }
    if (!readonly) {
      rejectMutable++;
      continue;
    }
    if (loads.empty())
      continue;

    // Try to work out a low-cost representation.
    BvExpr *correct = nullptr;
    int c0 = 0, c1 = 0;
    for (auto expr : candidates) {
      // We need to ensure that for all `i <= size`, the expression is correct.
      // We use SMT solver to find out the constants.

      // Solvers cannot be reused currently. Don't know how to improve it.
      BvSolver solver;
      // Find out the constants by assigning some value to `i`.
      int i = size / 2;
      solver.assign("x", i);
      auto vi = ctx.create(BvExpr::Const, ptr[i]);
      auto eq = ctx.create(BvExpr::Eq, expr, vi);

      // Validate that every element is correct.
      if (!solver.infer(eq))
        continue;

      bool good = true;
      for (int i = 0; i < size; i++) {
        if (solver.eval(expr, { { "x", i } }) != ptr[i]) {
          good = false;
          break;
        }
      }
      if (good) {
        correct = expr;
        if (solver.has("c0"))
          c0 = solver.extract("c0");
        if (solver.has("c1"))
          c1 = solver.extract("c1");
        break;
      }
    }

    if (!correct) {
      rejectNoFormula++;
      continue;
    }

    bool synthesizedThisArray = false;
    auto snapshot = loads;
    for (auto load : snapshot) {
      if (!load || !load->getParent())
        continue;
      auto index = resolveIndexValue(load->DEF(0), k, load, builder, pointerPhiCache);
      if (!index) {
        rejectNonAffineIndex++;
        continue;
      }

      builder.setBeforeOp(load);
      auto replacement = reconstruct(correct, index, c0, c1);
      load->replaceAllUsesWith(replacement);
      load->erase();
      loadsReplaced++;
      synthesizedThisArray = true;
    }
    if (synthesizedThisArray)
      arraysSynthesized++;
  }
}
